lzc-sdk-version: "0.1"
name: TTSFM
package: cloud.lazycat.community.app.ttsfm
version: 1.1.1
description: TTSFM 是一个逆向工程实现的 API 服务器，完全兼容 OpenAI 的文本转语音(TTS)接口
homepage: https://github.com/dbccccccc/ttsfm
author: dbccccccc
application:
  subdomain: ttsfm
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://ttsfm:7000/
services:
  ttsfm:
    image: docker.hlmirror.com/dbcccc/ttsfm:v1.1.1
    environment:
      - HOST=0.0.0.0
      - PORT=7000
      - VERIFY_SSL=true
      - USE_PROXY=true
      - PROXY_API_URL=https://proxy.scdn.io/api/get_proxy.php
      - PROXY_PROTOCOL=http
      - PROXY_BATCH_SIZE=5
      - MAX_QUEUE_SIZE=100
